# Generated by Django 3.0.5 on 2020-04-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcatcc', '0002_auto_20200424_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='user',
        ),
        migrations.AddField(
            model_name='agreement',
            name='email',
            field=models.EmailField(default='holomanga@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
