# Generated by Django 3.0.5 on 2020-04-26 15:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tcatcc', '0003_auto_20200424_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tcatcc.Item')),
            ],
        ),
    ]
